# Dockerfile for Go Project Scaffolder
FROM golang:1.24-alpine

WORKDIR /app

# Copia o gerador para dentro da imagem
COPY generator.go .

# Define o ponto de entrada para rodar o gerador
ENTRYPOINT ["go", "run", "generator.go"]
